# Generated by Django 5.1.3 on 2024-11-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
